#!/usr/bin/env node
/**
 * Guided Railway deploy for core-api + worker (ADR-002).
 *
 * Usage:
 *   node scripts/railway-deploy.mjs                 # checklist + generate secrets
 *   node scripts/railway-deploy.mjs --migrate       # run Alembic against DATABASE_URL
 *   node scripts/railway-deploy.mjs --execute       # railway login/init/up (interactive)
 *
 * Env (or data/deploy/railway.env after first run):
 *   DATABASE_URL          Neon postgres URL
 *   API_SECRET_KEY        shared admin secret
 *   SYNTH_API_BASE_URL    set after first core-api deploy
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DEPLOY_DIR = resolve(ROOT, "data", "deploy");
const DEPLOY_ENV = resolve(DEPLOY_DIR, "railway.env");
const MIGRATE = process.argv.includes("--migrate");
const EXECUTE = process.argv.includes("--execute");

function loadDeployEnv() {
  if (existsSync(DEPLOY_ENV)) {
    applyEnvFile(DEPLOY_ENV);
  }
  const rootEnv = resolve(ROOT, ".env");
  if (!existsSync(rootEnv)) return;
  const parsed = parseEnvFile(rootEnv);
  const db = parsed.DATABASE_URL ?? "";
  if (db && !db.includes("localhost") && !db.includes("USER:PASS") && !process.env.DATABASE_URL) {
    process.env.DATABASE_URL = db;
  }
}

function parseEnvFile(path) {
  const out = {};
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function applyEnvFile(path) {
  for (const [key, val] of Object.entries(parseEnvFile(path))) {
    if (!process.env[key]) process.env[key] = val;
  }
}

function run(cmd, args, opts = {}) {
  const { timeout, ...rest } = opts;
  const r = spawnSync(cmd, args, {
    cwd: ROOT,
    stdio: "inherit",
    shell: true,
    timeout: timeout ?? 120_000,
    ...rest,
  });
  if (r.error?.code === "ETIMEDOUT") return false;
  return r.status === 0;
}

function railwayBin() {
  const local = resolve(ROOT, "node_modules", "@railway", "cli", "bin", "railway.js");
  return existsSync(local) ? local : null;
}

function railway(args) {
  const bin = railwayBin();
  if (bin) return run("node", [bin, ...args]);
  return run("pnpm", ["exec", "railway", ...args]);
}

function ensureSecrets() {
  mkdirSync(DEPLOY_DIR, { recursive: true });
  loadDeployEnv();
  const existing = existsSync(DEPLOY_ENV) ? parseEnvFile(DEPLOY_ENV) : {};
  const currentKey = existing.API_SECRET_KEY ?? process.env.API_SECRET_KEY ?? "";
  const needsKey =
    !currentKey || currentKey.includes("change-me") || currentKey.length < 32;
  if (needsKey) {
    process.env.API_SECRET_KEY = randomBytes(32).toString("hex");
  } else {
    process.env.API_SECRET_KEY = currentKey;
  }
  const lines = [
    "# Generated by scripts/railway-deploy.mjs — do not commit",
    `# DATABASE_URL=${process.env.DATABASE_URL ?? "postgresql+psycopg://USER:PASS@HOST/neondb"}`,
    `API_SECRET_KEY=${process.env.API_SECRET_KEY}`,
    "ENVIRONMENT=production",
    "SYNTH_ARTIFACTS_DIR=/data/artifacts",
    "SYNTH_CORPORA_DIR=/data/corpora",
    `# SYNTH_API_BASE_URL=https://YOUR-SERVICE.up.railway.app`,
  ];
  writeFileSync(DEPLOY_ENV, lines.join("\n") + "\n", "utf8");
  console.log(`\nWrote ${DEPLOY_ENV}`);
  console.log(`API_SECRET_KEY=${process.env.API_SECRET_KEY}\n`);
}

function check(name, ok, fix) {
  console.log(`${ok ? "✓" : "✗"} ${name}${ok ? "" : ` — ${fix}`}`);
  return ok;
}

loadDeployEnv();

console.log("Blue Hen RE · Railway deploy (ADR-002)\n");

const dockerOk = run("docker", ["version"], { stdio: "pipe", timeout: 5_000 });
const vercelOk = run("vercel", ["whoami"], { stdio: "pipe", timeout: 15_000 });
const uvOk = run("uv", ["--version"], { stdio: "pipe", timeout: 10_000 });
const railwayOk = (() => {
  const bin = railwayBin();
  if (bin) return run("node", [bin, "whoami"], { stdio: "pipe", timeout: 15_000 });
  return run("pnpm", ["exec", "railway", "whoami"], { stdio: "pipe", timeout: 15_000 });
})();

check("Docker", dockerOk, "optional for local parity; not required for Railway deploy");
check("Vercel CLI", vercelOk, "npm i -g vercel && vercel login");
check("uv", uvOk, "install uv");
check("Railway CLI", railwayOk, "pnpm add -D @railway/cli && pnpm exec railway login");

ensureSecrets();

if (MIGRATE || EXECUTE) {
  if (!process.env.DATABASE_URL || process.env.DATABASE_URL.includes("USER:PASS")) {
    console.error("\nSet DATABASE_URL in data/deploy/railway.env (Neon console → Connection string).");
    console.error("Use postgresql+psycopg://… form (SQLAlchemy driver).");
    process.exit(1);
  }
}

if (MIGRATE) {
  console.log("\n→ Running Alembic migrate against Neon…");
  const ok = run("pnpm", ["db:migrate"], {
    env: { ...process.env, DATABASE_URL: process.env.DATABASE_URL },
  });
  process.exit(ok ? 0 : 1);
}

console.log(`
── Step 1: Neon DATABASE_URL ──
1. Open https://console.neon.tech (or Vercel → Storage → Neon)
2. Create project "bluehenre-prod" · copy pooled connection string
3. Edit data/deploy/railway.env → set DATABASE_URL=postgresql+psycopg://…
4. Run: pnpm deploy:railway:migrate

── Step 2: Railway project (two services) ──
1. pnpm deploy:railway:exec          # logs in + creates/links project
2. In Railway dashboard → New Service → GitHub repo (same repo)
   • Service A "core-api": uses railway.toml (start: api), enable public networking
   • Service B "worker": Custom Start Command → worker, RAM ≥ 4 GB, attach volume /data/artifacts
3. Shared variables (both services) — paste from data/deploy/railway.env:
   DATABASE_URL, API_SECRET_KEY, ENVIRONMENT=production

── Step 3: Migrate + smoke test ──
pnpm deploy:railway:migrate
curl $SYNTH_API_BASE_URL/healthz

── Step 4: Workspaces + Vercel ──
$env:SYNTH_API_BASE_URL="https://…"; $env:API_SECRET_KEY="…"; pnpm bootstrap:orgs
pnpm vercel:link-fleet:exec
pnpm vercel:env-fleet:exec
`);

if (!EXECUTE) {
  console.log("Next: fill DATABASE_URL in data/deploy/railway.env, then pnpm deploy:railway:migrate");
  console.log("When ready for Railway CLI: pnpm deploy:railway:exec\n");
  process.exit(0);
}

console.log("→ Installing @railway/cli (dev) if needed…");
run("pnpm", ["add", "-D", "@railway/cli"], { stdio: "pipe" });

console.log("\n→ Railway login (browser opens if needed)…");
if (!railway(["whoami"])) {
  if (!railway(["login"])) process.exit(1);
}

console.log("\n→ Link or create Railway project…");
if (!existsSync(resolve(ROOT, ".railway"))) {
  if (!railway(["init", "--name", "bluehenre"])) process.exit(1);
}

console.log("\n→ Setting shared variables on linked service…");
for (const key of ["DATABASE_URL", "API_SECRET_KEY", "ENVIRONMENT", "SYNTH_ARTIFACTS_DIR"]) {
  const val = process.env[key];
  if (!val) continue;
  railway(["variables", "set", `${key}=${val}`]);
}

console.log("\n→ Deploying core-api (Dockerfile + railway.toml)…");
if (!railway(["up", "--detach"])) process.exit(1);

console.log(`
✓ Deploy triggered. In Railway dashboard:
  1. Add second service "worker" from same repo, start command: worker
  2. Copy shared env vars to worker · mount volume at /data/artifacts
  3. Copy core-api public URL → data/deploy/railway.env SYNTH_API_BASE_URL
  4. pnpm bootstrap:orgs && pnpm vercel:env-fleet:exec
`);
